### ISSUE TITLE
Get list of Disqus discussions from maerkers list and show them on the map

### ISSUE THREAD

**Issue by samuelregev** [samuelregev/anywayAndroidApp#33]
Following #9

**Comment by danielhers** [comment]
Depends on https://github.com/hasadna/anyway/issues/249
Discussion markers will be included in the list of markers fetched from the `/markers` route, but they will have `type=2`.
The Disqus identifier for each marker is `(marker.latitude, marker.longitute)`, and the app shortname is `anyway-feedback` (see https://github.com/hasadna/anyway/blob/master/templates/index.html#L220).

**Comment by samuelregev** [comment]
close by 07ed56306693b8b6acfd111255a1671f471e935d
