### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by danielhers** [samuelregev/anywayAndroidApp#34]
Clicking the search icon opens a dialog, but any address I entered resulted in an error message that it was not found.

**Comment by samuelregev** [comment]
It working fine for me. 
can you provide some datails about your device? (android version, device model etc.)?

**Comment by danielhers** [comment]
It's Meizu MX4, Android 4.4.2. Which address worked for you?

**Comment by samuelregev** [comment]
almost everything i tried, even if i just write "שלום" i'm getting this:
https://www.dropbox.com/s/o50gk4r3k1rz689/device-2015-03-27-104640.png?dl=0

**Comment by danielhers** [comment]
Strange. I'm getting this:

**Comment by samuelregev** [comment]
tnx, i'll look into it

**Comment by samuelregev** [comment]
I'll try to use google geocode webservice
http://maps.google.com/maps/api/geocode/json?language=iw&region=il&address=%D7%A9%D7%9C%D7%95%D7%9D

(daniel - please ignore this msg)
