### ISSUE TITLE
Enable lower zoom levels

### ISSUE THREAD

**Issue by danielhers** [samuelregev/anywayAndroidApp#35]
Currently zooming out beyond a certain point triggers the app to automatically zoom back in. It should be possible to zoom out, but to avoid the performance hit caused by loading all the markers by performing clustering of nearby markers, like we do on the web app (it still requires improvements there too, since the clustering is performed client-side and all the accidents still need to be sent. We want to do server-side clustering).

**Comment by samuelregev** [comment]
Lower zoom levels enabled, but below zoom level 16 the app does not fetch new data.
the app shows a message to zoom in but doesn't zoom in automatically.
