### ISSUE TITLE
Show marker description fields separately

### ISSUE THREAD

**Issue by danielhers** [samuelregev/anywayAndroidApp#50]
Depends on https://github.com/hasadna/anyway/issues/192
When the description is split in the model to separate fields (see https://github.com/hasadna/anyway/pull/254), the Android app will need to handle them properly.

**Comment by samuelregev** [comment]
Is there an option to either delay this process or when implementing it keep in some way access to the old markers?
(for example oway.org.il/?markers..... will be the same. add new path to oway.org.il/?marker_v2?.... that the website will use and delete the old one only after the app update process will complete)

Two reasons:
1. I'm afraid it will happen too close to my final project review (at the beginning of July).
2. We need to think about our 60(and growing) android clients that will still use the app using the old markers json structure. (it can take hours until the android system notify user about and nothing assure us that the user will update right away)

**Comment by danielhers** [comment]
How about we just leave the description field for now too, and you can
choose whether to use it or the separate fields?

**Comment by samuelregev** [comment]
That will do it, thanks

**Comment by samuelregev** [comment]
Note to self:
https://github.com/hasadna/anyway/commit/95be025ebaa51124d7943adf232ca7db105de3af

**Comment by samuelregev** [comment]
I will implement this during July, after My final project submission.
need to re-open this in hasadna/anywayAndroidApp
